import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse7201 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.setTargetPath(null);
}
}